export default {
    'GET_LIST_OF_REPOS': 'GET_LIST_OF_REPOS',
    'GET_LIST_OF_COMMITS': 'GET_LIST_OF_COMMITS',
    'REPOS_FETCH_SUCCESS': 'REPOS_FETCH_SCUCCESS',
    'COMMITS_FETCH_SUCCESS': 'COMMITS_FETCH_SUCCESS',
    'GET_LIST_OF_BRANCHES': 'GET_LIST_OF_BRANCHES',
    'BRANCHES_LIST_FETCH_SUCCESS': 'BRANCHES_LIST_FETCH_SUCCESS',
    'CHANGE_REPOS_SORT_BY_VALUE': 'CHANGE_REPOS_SORT_BY_VALUE',
    'CHANGE_BRANCH': 'CHANGE_BRANCH',
    'CHANGE_SELECTED_REPO': 'CHANGE_SELECTED_REPO',
    'CHANGE_SELECTED_REPO_SUCCESS': 'CHANGE_SELECTED_REPO_SUCCESS',
    'UPDATE_COMMITS_LIST': 'UPDATE_COMMITS_LIST',
    'SET_ERROR_STATE': 'SET_ERROR_STATE'
}